project_id = "rgufivgtyonitgjlozog"

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.delete-account]
verify_jwt = true

[functions.send-game-reminders]
verify_jwt = false

[functions.send-game-announcements]
verify_jwt = false
